version: '3.4'

services:
  discord-ttl:
    # directly using an image instead of building our own
    image: node:16-alpine
    working_dir: /usr/src/app
    env_file:
      - .env
    # runs yarn at runtime so mounts are active
    command: sh -c "ls -al && yarn --no-progress && yarn start"
    # mounting our API source directory
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
